template = ""
rev_id = 299
template_sha = "c2c940ccf19bf74ce9b697c688363766fc219a10"

[replacements]
__GLOTTOLOG_ID__ = "uduk1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-udu"
__UND2C__ = "udu"
__UNDEFINED__ = "Uduk"
__UND__ = "udu"
