template = ""
rev_id = 306
template_sha = "f3e6a329b1ec285a2a4b0abe3f024861cdd4e876"

[replacements]
__GLOTTOLOG_ID__ = "uduk1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-udu"
__UND2C__ = "udu"
__UNDEFINED__ = "Uduk"
__UND__ = "udu"
