template = ""
rev_id = 344
template_sha = "5adf8b2fc54441e99d8cd7357dc342d2e77ed5ac"

[replacements]
__GLOTTOLOG_ID__ = "uduk1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-udu"
__UND2C__ = "udu"
__UNDEFINED__ = "Uduk"
__UND__ = "udu"
